void init_timer0(void);
void delay_ms(unsigned int t_ms);
void move_F_PB();
void move_B_PB();
void move_F_PD();
void move_B_PD();
void move_same_time_B();
void move_same_time_F();
void move_Center_From_X2();
void make_step_Y(_Bool direction);
void make_step_X(_Bool direction);
void move_radial(int radius);